-- CREATE TABLE "user"(
--                         id SERIAL PRIMARY KEY,
--                         user_name VARCHAR(50) NOT NULL,
--                         password VARCHAR(50) NOT NULL,
--                         active BOOLEAN NOT NULL,
--                         roles VARCHAR(50) NOT NULL
-- );
--
-- INSERT INTO "user" (id, user_name, password, active, roles) VALUES
--                                                                (33, 'фффффф', 'фффффф', true, 'USER'),
--                                                                (44, 'ййй', 'ййй', true, 'USER');
--
-- INSERT INTO user_profile (id, user_name, theme, summary, first_name, last_name, email, phone, designation) VALUES
--                                                                                                                (33, 'фффффф', 1, 'Developed the theory of relativity, one of the two pillars of modern physics. My work is also known for its influence on the philosophy of science.', 'Albert', 'Einstein', 'einstein@gmail.com', '111-111-1111', 'Theoretical physicist'),
--                                                                                                                (44, 'ййй', 2, 'Widely recognised as one of the most influential scientists of all time and as a key figure in the scientific revolution', 'Isaac', 'Newton', 'newton@gmail.com', '222-222-2222', 'Mathematician, physicist, astronomer, theologian, and author');